- id: '1699304421771'
  alias: Hønserommet
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
    id: waketime
  - platform: time
    at: '20:00:00'
    id: bedtime
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - waketime
    then:
    - type: turn_on
      device_id: 906900c885e6381e32dce88394734b04
      entity_id: f0688ffd68a93152dcaaf11d52d4641d
      domain: switch
    - type: turn_on
      device_id: 488150fac0782aa95eece8640680b875
      entity_id: c7f08ae8cb808850c3f9686f3d91d58f
      domain: light
  - if:
    - condition: trigger
      id:
      - bedtime
    then:
    - type: turn_off
      device_id: 906900c885e6381e32dce88394734b04
      entity_id: f0688ffd68a93152dcaaf11d52d4641d
      domain: switch
    - type: turn_off
      device_id: 488150fac0782aa95eece8640680b875
      entity_id: c7f08ae8cb808850c3f9686f3d91d58f
      domain: light
  mode: single
- id: '1701083916838'
  alias: Siste bølla rengjøring
  description: ''
  trigger:
  - platform: device
    device_id: cf405abdb3db983b2363afe514710755
    domain: vacuum
    entity_id: 7ade79469d4c6a9c497b8b09f62a280d
    type: cleaning
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
    target:
      entity_id: input_datetime.bolla_last_cleanup_start
  mode: single
- id: '1701084748758'
  alias: Lenge siden sist støvsuger har kjørt
  description: ''
  trigger:
  - platform: time_pattern
    hours: '1'
  condition:
  - condition: template
    value_template: '{{ now() >= state_attr(''input_datetime.bolla_last_cleanup_start'',
      ''timestamp'') | as_datetime + timedelta(days=5) }}'
  action:
  - service: notify.mobile_app_max_iphone_11_max_pro
    data:
      message: Det er mer en 5 dager siden siste vask. Sjekk støvsuger
  mode: single
- id: '1702030795048'
  alias: Device unavailable notification
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 9de618a93639561af56d81dffba66e01
    entity_id: 01038997ef4383bbc7d29ad81f18e55e
    domain: sensor
    above: 1
  condition: []
  action:
  - service: notify.mobile_app_pixel_8_pro
    data:
      message: Noen enheter har blitt utilgjengelig
  mode: single
- id: '1702031266203'
  alias: Watchman update
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: watchman.report
    data:
      create_file: true
      parse_config: false
      chunk_size: false
  mode: single
